#!/bin/bash

# This script passes system environment variables to Vite
source ~/.zshrc

# Pass the environment variables to the Vite dev server
VITE_SUPABASE_URL=$SUPABASE_URL_TM \
VITE_SUPABASE_SERVICE_KEY=$SUPABASE_SERVICE_KEY_TM \
VITE_SUPABASE_API_KEY=$SUPABASE_API_KEY_TM \
VITE_SUPABASE_SECRET_KEY=$SUPABASE_SECRET_KEY_TM \
VITE_BASE_API_URL=$BASE_API_URL \
VITE_DEV_BASE_API_URL=$BASE_API_DEV_URL \
VITE_APP_URL=$APP_URL \
VITE_DEV_APP_URL=$DEV_APP_URL \
VITE_ENV_MODE=$ENV_MODE \
npm run dev