// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzxbzyntvnqtkuvnzovu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6eGJ6eW50dm5xdGt1dm56b3Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MDEwNTYsImV4cCI6MjA2NTk3NzA1Nn0.PH8jVjFrRHqH2u0_ypw8Eb0YkwovWtS50CgrZ7jLcTA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);